### ISSUE TITLE
Transfer this repo to Hyperledger

### ISSUE THREAD

**Issue by jtraglia** [ConsenSys/errorprone-checks#14]
So it seems that these checks were originally developed by several Besu contributors. I think it would make sense to transfer this repository to the Hyperledger organization, preferably under the same `errorprone-checks` name. I'm unsure of what would need to be done before this, but at a minimum it would require some license file banner changes first.

Associated with:
* https://github.com/hyperledger/besu/pull/4754

**Comment by ajsutton** [comment]
There's been multiple copies of these checks floating around.  They were originally developed by ConsenSys as part of Pantheon and duplicated in Teku, Teku then added some new ones, they were duplicated again to Web3Signer. Somewhere in that sequence Pantheon was donated to HyperLedger and renamed to Besu, then this repo was created to avoid all the duplication.

Moving this to HyperLedger is a very poor fit for Teku and Web3Signer as while there's some people who work on them who are also Besu contributors mostly they're not. So we'd be unable to continue developing these checks and most importantly would be unable to do releases in a timely manner so changes here can actually be used.

With Besu contributors raising objections to using this repo, it becomes impossible to avoid duplication and meet the needs of all the projects so Besu may as well just keep using the checks directly in it's repo to avoid managing dependencies/releases etc.
